// Code generated by "stringer -type=Format"; DO NOT EDIT.

package format

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Terraform-0]
	_ = x[Crossplane-1]
}

const _Format_name = "TerraformCrossplane"

var _Format_index = [...]uint8{0, 9, 19}

func (i Format) String() string {
	if i < 0 || i >= Format(len(_Format_index)-1) {
		return "Format(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Format_name[_Format_index[i]:_Format_index[i+1]]
}
